In [1]:
import numpy as np

In [ ]:
def heapsort(iterable):
    build_heap(iterable)
    for idx in np.
    
def build_heap(iterable):
    ...
    
    
def heapify(iterable, idx, max_idx):
    ...

In [31]:
arr[[0, -1]] = arr[[-1, 0]]

In [32]:
arr

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [39]:
arr = np.arange(10).reshape(2, 5)
for i in zip(*np.indices(arr.shape)):
    print(i)

(array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4]))
(array([1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4]))


In [40]:
np.indices(arr.shape)

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])